from yacs.config import CfgNode as CN

_C = CN()

_C.OUT_DIR = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/Standard_Pipeline+MASK_SIAM+CASS+LoRA+Fusion/output_esdg_h100"
_C.USE_CUDA = True
_C.SEED = 42
_C.num_workers = 8
_C.VERBOSE = True

_C.MODEL = CN()
_C.MODEL.PRETRAINED = True
_C.MODEL.PRETRAINED_PATH = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/checkpoints/resnet50-19c8e357.pth"
_C.ALGORITHM = "CASS_GDRNet"
_C.BACKBONE = "resnet50"
_C.DG_MODE = "ESDG"

_C.DATASET = CN()
_C.DATASET.ROOT = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/GDR_Formatted_Data"
_C.DATASET.NUM_CLASSES = 5
_C.DATASET.SOURCE_DOMAINS = ["MESSIDOR"]
_C.DATASET.TARGET_DOMAINS = ["APTOS", "DDR", "DEEPDR", "FGADR", "IDRID", "RLDR", "EYEPACS"]

_C.EPOCHS = 100
_C.LEARNING_RATE = 0.00045
_C.BATCH_SIZE = 16
_C.WEIGHT_DECAY = 5e-4
_C.MOMENTUM = 0.9
_C.DROP_LAST = False
_C.DROP_OUT = 0.0
_C.LOG_STEP = 5
_C.VAL_EPOCH = 1

_C.GDRNET = CN()
_C.GDRNET.BETA = 0.5
_C.GDRNET.TEMPERATURE = 0.01
_C.GDRNET.SCALING_FACTOR = 4.0
_C.GDRNET.GAMMA = 1.0
_C.GDRNET.LORA_R = 8
_C.GDRNET.LORA_ALPHA = 16.0
_C.GDRNET.DINOV3_PATH = "/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/checkpoints/dinov3_vitb16"

_C.TRANSFORM = CN()
_C.TRANSFORM.NAME = []
_C.TRANSFORM.AUGPROB = 0.5
_C.TRANSFORM.COLORJITTER_B = 1
_C.TRANSFORM.COLORJITTER_C = 1
_C.TRANSFORM.COLORJITTER_S = 1
_C.TRANSFORM.COLORJITTER_H = 0.05

_C.OPTIM = CN()
_C.OPTIM.NAME = ""
_C.RANDOM = False
_C.OVERRIDE = True